### ISSUE TITLE
Implement Optional Extra Mouse Button Support

### ISSUE THREAD

**Issue by viluon** [CCEmuX/CCEmuX#114]
Commit 532a5f004678d5d5fcdc2c3c58f55cd6de9728be removed the possibility of catching extra mouse button events (such as forward and backward navigation buttons on computer mice and some [actual mice](https://i.imgur.com/7siVHlc.jpg)). While this brought CCEmuX yet another step closer to vanilla, I think it would be quite good to add a config option to revert to the previous behaviour.

While I'm at it, I also suggest adding a config option for extra keyboard button support, namely the <kbd>ESC</kbd> key.

**Comment by SquidDev** [comment]
*Sigh*. I knew this was going to be an issue before I even created the commit. Everything always breaks _someone's_ workflow.

However, I think you've hit the nail on the head - CCEmuX aims to emulate vanilla ComputerCraft as closely as possible, and so I'd like to avoid adding "hidden extras", even if gated behind config options. Now, obviously there are exceptions to this, where such changes make the development experience better (such as the `ccemux` command), but I don't think the changes here are tangible enough to merit adding it.

I'll leave this open to allow the other developers to chip in, but I think this is something I'd rather see added to the main mod/CC:T before integrating it here.

**Comment by dmarcuse** [comment]
I'm inclined to agree with @SquidDev on this one: The primary goal of CCEmuX is to match the behavior of CC/CC:T. I think when I originally wrote the code handling mouse buttons, I added the fallback behavior because I was too lazy to start up MC and test how it actually worked - I wasn't intentionally implementing it differently.

**Comment by viluon** [comment]
@SquidDev it didn't break my workflow. None of my code was relying on this accidental feature. I just think more interactivity opens gates for more ergonomic applications, whether it's mouse buttons or horizontal scrolling (https://github.com/dan200/ComputerCraft/issues/569). If this proposal is better suited for CC:T (I regard the official ComputerCraft repository as stale), I'll gladly close this issue and open a new one there.

However, the <kbd>ESC</kbd> case seems a bit different. IIRC, there has been some discussion about this on the official forums, and Dan himself voiced his disapproval of a similar event (whether CC:T takes a similar stance is another matter entirely). This makes sense in-game, for obvious reasons, but on CCEmuX, the <kbd>ESC</kbd> key doesn't do anything, as far as I'm concerned. Yet it is a crucial key in desktop and terminal applications alike. What are the developers' thoughts on this? Would you be in favour of adding support for another key event? Should all of this conversation move to CC:T?

**Comment by SquidDev** [comment]
> I just think more interactivity opens gates for more ergonomic applications

It does, but the issue is that one is then writing _CCEmuX_ specific applications, rather than ones for ComputerCraft. CCEmuX does not aim to be an environment in itself - there are far better fantasy consoles out there already.

I don't really see how <kbd>ESC</kbd> is any different. There is no situation where such an event is queued within the game, and therefore there is no situation where it should be queued within the emualator. I don't want to start introducing behaviour that users then come to rely on, only for it to not occur within the actual game.

As far as adding the behaviour to CC(:T), my stance is to create an issue on the main CC repo, unless it's an issue/enhancmenet to a pre-existing CC:T feature. There's more people following it, so one is more likely to get feedback from others.
