### ISSUE TITLE
Feature Request: implement io.popen

### ISSUE THREAD

**Issue by hugeblank** [CCEmuX/CCEmuX#116]
ok yeah this is practically impossible to do since you're basically plugging in a CC jar file, but theoretically couldn't this be done with enough bodging? I'd love to see this as it would expand the functionality of ccemux and allow for practicality beyond the scope of CC. Sure this may not be the intended direction of the project, but hey it was worth a proposal.

**Comment by Lustyn** [comment]
...running a command?

**Comment by hugeblank** [comment]
yeah, like the generic lua implementation for linux does. IE: `io.popen("ls -l /")`

**Comment by dmarcuse** [comment]
I feel that this is out-of-scope for core CCEmuX, and can be trivially implemented with a plugin anyways, since plugins can implement both Lua APIs and custom ROM entries. 

This also completely breaks out of the (admittedly weak) sandbox that CC creates, which is another reason I don't want it to be implemented in core CCEmuX.
