### ISSUE TITLE
Release JAR changed hash

### ISSUE THREAD

**Issue by viluon** [CCEmuX/CCEmuX#167]
See NixOS/nixpkgs#272193

The [tweaked JAR](https://emux.cc/versions/989cfe52/CCEmuX-cct.jar) for revision 989cfe52a0458b991e0a7d87edec81d3fef472ac has changed:
```diff
- sha256-B9Zan6wpYnUtaNbUIrXvkchPiEquMs9R2Kiqg85/VdY=
+ sha256-nna5KRp6jVLkbWKOHGtQqaPr3Zl05mVkCf/8X9C5lRY=
```

The [untweaked JAR](https://emux.cc/versions/989cfe52/CCEmuX-cc.jar) did not change. At first I suspected a hash collision, but there only seems to be one commit with the `989cfe52` prefix.

What happened?

**Comment by SquidDev** [comment]
It looks like the jar was [rebuilt on 2023-08-16](https://autoclave.squiddev.cc/job/2023-08-16/201915-buildkit-build-a4767c) due to the upstream docker image changing.

> The untweaked JAR did not change

We don't support normal CC any more. In order to preserve compatibility with the launcher, all recent versions just fallback to the last available version (b9c413d9).

I'm going to be honest, I don't think shipping CCEmuX as a Nix package is a very good idea. Unlike my maven, I don't really make any guarantees about the stability of the CCEmuX jars (except that the exist) - they're only there for the launcher.

Ideally the actual build could just be done via Nix - I have had a look at gradle2nix in the past, but haven't had much luck.

**Comment by SquidDev** [comment]
I have tweaked some of Gradle settings in b60085350cfd159ba1be08697476fc46ed2198a7 to make the produced jar a little more reproducible.

**Comment by viluon** [comment]
A full Nix build would be great, but that's a larger refactor. Thanks for the steps towards reproducibility though.
