### ISSUE TITLE
Is this available to JDK 10?

### ISSUE THREAD

**Issue by jmc529** [CCEmuX/CCEmuX#98]
Maybe I'm just being dumb, but when I tried setting this up, via /.gradlew build, I get the error _Execution failed for task ':plugin-api:compileJava'_. I checked my JAVA_HOME variable as the error suggests and ensured it points to the jdk's path; _C:\Progra~1\Java\jdk-10.0.1_ in this case. Could you give me insight to what I'm doing wrong should I download Java 8 or 9?

Edit: also I apologize if this is the wrong method for asking this sort of question.

**Comment by Lemmmy** [comment]
not yet sorry download java 8

**Comment by SquidDev** [comment]
We support Java 9, so I'd be surprised if anything major changed since then (though ape is probably the person to ask on that front). Can you post the full result the Gradle command? 

That being said, as Lemmmy says, it's probably better to downgrade to Java 8. I think most of us are targeting that version, as Minecraft doesn't play especially well with later ones.

**Comment by Lemmmy** [comment]
due to java's new "move fast, break things" strategy it's becoming increasingly harder for projects to keep up with new versions :(

**Comment by dmarcuse** [comment]
Java 10 should work, can you give us the full error log?

**Comment by jmc529** [comment]
So I figured it out: I was just being dumb. I didn't have the proper permissions set for java and gradle couldn't access it. Sorry for the fuss. Also it seems to work fine with Java 10
